### ISSUE TITLE
建议GuzzleHttp 支持到 7

### ISSUE THREAD

**Issue by SuperChenYun** [TencentCloud/tencentcloud-im-sdk-php#3]
GuzzleHttp6 
Thinkphp6 
封装了个工厂类统一设置 client 及调用工厂类 记录日志的时候总是拿不到返回信息

**Comment by shifpeng** [comment]
1.0.7临时增加了guzzlehttp/guzzle 7 的兼容，后面的版本会升级PHP版本到 7.x，guzzlehttp/guzzle版本也会同步升级，看看目前的版本是否能满足你的需求
