### ISSUE TITLE
guzzlehttp/guzzle 这个不升级, 根本没法用

### ISSUE THREAD

**Issue by bakawi** [TencentCloud/tencentcloud-im-sdk-php#4]
你要是不升级,我就拉下来自己搞了

**Comment by lishuncoder** [comment]
> 你要是不升级,我就拉下来自己搞了

老铁，我正在写一个guzzle7的包，有无兴趣一起做啊，其实没什么，都是苦力活，一个人干太累

**Comment by shifpeng** [comment]
> 你要是不升级,我就拉下来自己搞了

具体是什么问题导致的没法使用，1.0.7临时增加了guzzlehttp/guzzle 7 的兼容，后面的版本会升级PHP版本到 7.x，guzzlehttp/guzzle版本也会同步升级，看看目前的版本是否能满足你的需求

**Comment by lishuncoder** [comment]
> > 你要是不升级,我就拉下来自己搞了
> 
> 具体是什么问题导致的没法使用，1.0.7临时增加了guzzlehttp/guzzle 7 的兼容，后面的版本会升级PHP版本到 7.x，guzzlehttp/guzzle版本也会同步升级，看看目前的版本是否能满足你的需求

多半是因为他那边组件已经定死了guzzle不能小于7，然后你们最新版本有无解决类型问题？

**Comment by lishuncoder** [comment]
> > 你要是不升级,我就拉下来自己搞了
> 
> 具体是什么问题导致的没法使用，1.0.7临时增加了guzzlehttp/guzzle 7 的兼容，后面的版本会升级PHP版本到 7.x，guzzlehttp/guzzle版本也会同步升级，看看目前的版本是否能满足你的需求

另外，加密组件那边已经升级到1.1了，你们这边不跟随吗？而且我看1.0和1.1的方法名并不一样

**Comment by shifpeng** [comment]
> 

什么类型问题

**Comment by shifpeng** [comment]
> > > 你要是不升级,我就拉下来自己搞了
> > 
> > 
> > 具体是什么问题导致的没法使用，1.0.7临时增加了guzzlehttp/guzzle 7 的兼容，后面的版本会升级PHP版本到 7.x，guzzlehttp/guzzle版本也会同步升级，看看目前的版本是否能满足你的需求
> 
> 多半是因为他那边组件已经定死了guzzle不能小于7，然后你们最新版本有无解决类型问题？

什么类型问题？

**Comment by lishuncoder** [comment]
> > > > 你要是不升级,我就拉下来自己搞了
> > > 
> > > 
> > > 具体是什么问题导致的没法使用，1.0.7临时增加了guzzlehttp/guzzle 7 的兼容，后面的版本会升级PHP版本到 7.x，guzzlehttp/guzzle版本也会同步升级，看看目前的版本是否能满足你的需求
> > 
> > 
> > 多半是因为他那边组件已经定死了guzzle不能小于7，然后你们最新版本有无解决类型问题？
> 
> 什么类型问题？

你可以查看我自己提的issue
